### ISSUE TITLE
Question: Passing unattended/silent switch to underlaying exe?

### ISSUE THREAD

**Issue by totszwai** [dkxce/MSILid4Exe#1]
Hello, 

I have an installer created via Inno Setup, little did I know, I had to support MSI too.
I am wondering, is there a way to relay the MSI slient or unattended install switches over to the underlaying Inno Setup installer?

I ran your tool, I think launchs the inner .exe installer, however I don't think any of the command line switch works?

**Comment by dkxce** [comment]
Hi.
MSILid uses the standard MSI toolkit which can unpack executable files from it and run them. Executable file runs by host process msiexec. But it does not pass selfstartup arguments in its, there is no such feature. You can either use CmdArgs in the xml config to pass fixed arguments to launch. Or write your own script for InnoSetup that defines the parent process and its environment or launch parameters, but it will not work correctly. The better way is prepare several executables: one for UI install and one for silent. And run them separately.

**PowerShell**:
>Get-CimInstance Win32_Process -Filter "Handle = '53252'" | fl Name,CommandLine
or
>Get-WmiObject -Query "SELECT CommandLine FROM Win32_Process WHERE ProcessID = 53252" |fl CommandLine
**Cmd**:
> wmic path Win32_Process where "Handle=53252" get Handle,CommandLine
or
> wmic process where "Handle=53252" get Handle,CommandLine
**GetParentProcessID**:
https://stackoverflow.com/questions/7909291/how-to-find-the-name-of-the-parent-program-that-started-us
